[package]
name = "prism_lsp"
edition.workspace = true
version.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
prism_compiler.workspace = true
tower-lsp-server.workspace = true
tokio.workspace = true
prism_input.workspace = true